Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment5.ViewModels;

namespace Assignment5.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        private Manager m = new Manager();

        // GET: Album
        public ActionResult Index()
        {
            return View(m.AlbumGetAll());
        }

        // GET: Album/Details/5
        public ActionResult Details(int? id)
        {
            AlbumWithDetailViewModel album = m.AlbumGetByID(id ?? 0);
            if (album == null)
                return HttpNotFound();
            else
                return View(album);
        }

        // GET: Album/{id}/AddTrack
        [Authorize(Roles = "Clerk")]
        [Route("Albums/{id}/AddTrack")]
        public ActionResult AddTrack(int? id)
        {
            AlbumWithDetailViewModel album = m.AlbumGetByID(id ?? 0);

            if (album == null)
                return HttpNotFound();

            TrackAddFormViewModel track = new TrackAddFormViewModel();
            track.AlbumName = album.Name;
            track.AlbumId = album.Id;
            track.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");

            return View(track);
        }

        // POST: Album/{id}/AddTrack
        [HttpPost]
        [Authorize(Roles = "Clerk")]
        [Route("Albums/{id}/AddTrack")]
        public ActionResult AddTrack(TrackAddViewModel newTrack)
        {
            if (!ModelState.IsValid)
                return View(newTrack);
            try
            {
                var addedTrack = m.TrackAdd(newTrack);
                if (addedTrack == null)
                    return View(newTrack);
                else
                    return RedirectToAction("Details", "Tracks", new { id = addedTrack.Id });
            }
            catch
            {
                return View(newTrack);
            }
        }
    }
}

Views/Albums/AddTrack.cshtml
@model Assignment5.ViewModels.TrackAddFormViewModel

@{
    ViewBag.Title = Model.AlbumName + " - Add Track";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Complete the Form, and click the Create button</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Composers, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Composers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Composers, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenreList, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="dropdown">
                @Html.DropDownListFor(model => model.GenreId, Model.GenreList, new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.GenreList, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AudioUpload, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AudioUpload, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AudioUpload, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.Hidden("AlbumId", Model.AlbumId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Album", "Details", "Album", new { id = Model.AlbumId }, new { @class = "btn btn-secondary btn-sm" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Albums/Details.cshtml
@model Assignment5.ViewModels.AlbumWithDetailViewModel

@{
    ViewBag.Title = Model.Name;
    var userAccount = new Assignment5.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
}

<h2 style="text-align: center">@ViewBag.Title</h2>

<br />

<table class="table table-borderless table-striped">
    <tr>
        <th>@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.ReleaseDate)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Coordinator, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Coordinator)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.UrlAlbum, htmlAttributes: new { @class = "control-label" })</th>
        <td><img src="@Model.UrlAlbum" alt="@Model.Name" style="width:100%; max-width:150px" /></td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Genre)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Depiction, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.Raw(Model.Depiction)</td>
    </tr>
</table>
<p>
    @if (userAccount.HasRoleClaim("Clerk"))
    {
        @Html.ActionLink("Add a new Track", "AddTrack", "Albums", new { id = Model.Id }, new { @class = "btn btn-secondary btn-sm" }); 
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Albums/Index.cshtml
@model IEnumerable<Assignment5.ViewModels.AlbumBaseViewModel>

@{
    ViewBag.Title = "Albums";
}

<h2 style="text-align: center">@ViewBag.Title</h2>

<table class="table table-borderless table-striped" style="table-layout: fixed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Coordinator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlAlbum)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Coordinator)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                <img src="@item.UrlAlbum" alt="@item.Name" style="width:100%; max-width:150px" />
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Albums", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
            </td>
        </tr>
    }

</table>