Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment5.ViewModels;

namespace Assignment5.Controllers
{
    [Authorize]
    public class ArtistsController : Controller
    {
        private Manager m = new Manager();

        // GET: Artist
        public ActionResult Index()
        {
            return View(m.ArtistGetAll());
        }

        // GET: Artist/Details/5
        public ActionResult Details(int? id)
        {
            ArtistWithMediaViewModel artist = m.ArtistGetByIDWithMedia(id ?? 0);
            if (artist == null)
                return HttpNotFound();
            else
                return View(artist);
        }

        // GET: Artist/Create
        [Authorize(Roles = "Executive")]
        public ActionResult Create()
        {
            ArtistAddFormViewModel artist = new ArtistAddFormViewModel();
            artist.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");
            return View(artist);
        }

        // POST: Artist/Create
        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Executive")]
        public ActionResult Create(ArtistAddViewModel newArtist)
        {
            if (!ModelState.IsValid)
                return View(newArtist);
            try
            {
                var addedArtist = m.ArtistAdd(newArtist);
                if (addedArtist == null)
                    return View(newArtist);
                else
                    return RedirectToAction("Details", new { id = addedArtist.Id });
            }
            catch
            {
                return View(newArtist);
            }
        }

        [Authorize(Roles = "Coordinator")]
        [Route("Artists/{id}/AddAlbum")]
        public ActionResult AddAlbum(int? id)
        {
            ArtistWithDetailViewModel artist = m.ArtistGetByID(id ?? 0);
            if (artist == null)
                return HttpNotFound();

            AlbumAddFormViewModel album = new AlbumAddFormViewModel();
            album.ArtistName = artist.Name;
            album.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");
            album.ArtistId = artist.Id;

            return View(album);
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Coordinator")]
        [Route("Artists/{id}/AddAlbum")]
        public ActionResult AddAlbum(AlbumAddViewModel newAlbum)
        {
            if (!ModelState.IsValid)
                return View(newAlbum);
            try
            {
                var addedAlbum = m.AlbumAdd(newAlbum);
                if (addedAlbum == null)
                    return View(newAlbum);
                else
                    return RedirectToAction("Details", "Albums", new { id = addedAlbum.Id });
            }
            catch
            {
                return View(newAlbum);
            }
        }

        [Authorize(Roles = "Executive")]
        [Route("Artists/{id}/AddMedia")]
        public ActionResult AddMedia(int? id)
        {
            ArtistWithDetailViewModel artist = m.ArtistGetByID(id ?? 0);

            if (artist == null)
                return HttpNotFound();

            MediaItemAddFormViewModel form = new MediaItemAddFormViewModel();
            form.ArtistId = artist.Id;
            form.ArtistInfo = $"{artist.Name}, Main Genre: {artist.Genre}";

            return View(form);
        }

        [HttpPost]
        [Authorize(Roles = "Executive")]
        [Route("Artists/{id}/AddMedia")]
        public ActionResult AddMedia(int? id, MediaItemAddViewModel newMedia)
        {
            if (!ModelState.IsValid && id.GetValueOrDefault() == newMedia.ArtistId)
                return View(newMedia);

            ArtistBaseViewModel addedMedia = m.ArtistMediaAdd(newMedia);

            if (addedMedia == null)
                return View(newMedia);

            return RedirectToAction("Details", new { id = addedMedia.Id });
        }
    }
}

Views/Artists/AddAlbum.cshtml
@model Assignment5.ViewModels.AlbumAddFormViewModel

@{
    ViewBag.Title = Model.ArtistName + " - Add Album";
}

<script src="//cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrlAlbum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrlAlbum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrlAlbum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenreList, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <div class="dropdown">
                @Html.DropDownListFor(model => model.GenreId, Model.GenreList, new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.GenreList, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Depiction, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Depiction, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Depiction, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.ArtistId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>CKEDITOR.replace('Depiction', { startupFocus: true });</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Artists/AddMedia.cshtml
@model Assignment5.ViewModels.MediaItemAddFormViewModel

@{
    ViewBag.Title = "Add Media";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Html.Raw(Model.ArtistInfo)</h4>
        @Html.HiddenFor(model => model.ArtistId)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Caption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentUpload, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Artists/Create.cshtml
@model Assignment5.ViewModels.ArtistAddFormViewModel

@{
    ViewBag.Title = "Create New Artist";
}

<script src="//cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<h2 style="text-align: center">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 style="text-align: center">Fill out the form, and press Create</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthOrStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthOrStartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthOrStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Executive, new { Value = "" })

    <div class="form-group">
        @Html.LabelFor(model => model.UrlArtist, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrlArtist, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrlArtist, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenreList, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var genre in Model.GenreList)
            {
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.GenreId, genre.Value)
                    @genre.Text
                </label>
            }
            @Html.ValidationMessageFor(model => model.GenreList, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Portrayal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Portrayal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Portrayal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>CKEDITOR.replace('Portrayal', { startupFocus: true });</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Artists/Details.cshtml
@model Assignment5.ViewModels.ArtistWithMediaViewModel

@{
    ViewBag.Title = Model.Name;
    var userAccount = new Assignment5.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
}

<h2 style="text-align: center">@ViewBag.Title</h2>

<br />

<table class="table table-borderless table-striped">
    <tr>
        <th>@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.BirthName, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.BirthName)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.BirthOrStartDate, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.BirthOrStartDate)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.UrlArtist, htmlAttributes: new { @class = "control-label" })</th>
        <td><img src="@Model.UrlArtist" alt="@Model.Name" style="width:100%; max-width:150px" /></td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Executive, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Executive)</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.DisplayFor(model => model.Genre)</td>
    </tr>
    <tr>
        <th><label class="control-label">Number of Albums</label></th>
        <td>@Model.Albums.Count()</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Portrayal, htmlAttributes: new { @class = "control-label" })</th>
        <td>@Html.Raw(Model.Portrayal)</td>
    </tr>
    @if (Model.MediaItems.Where(m => m.ContentType.Contains("image/")).Count() > 0)
    {


        foreach (var mediaItem in Model.MediaItems.Where(m => m.ContentType.Contains("image/")))
        {
            <tr>
                <th>@mediaItem.Caption</th>
                <td><img src="~/media/@mediaItem.StringId" alt="@mediaItem.Caption" title="@mediaItem.Caption" class="img-responsive img-rounded" width="200" /></td>
            </tr>
        }

    }
    @if (Model.MediaItems.Where(m => m.ContentType.Contains("audio/")).Count() > 0)
    {

        foreach (var mediaItem in Model.MediaItems.Where(m => m.ContentType.Contains("audio/")))
        {
            <tr>
                <th>@mediaItem.Caption</th>
                <td><audio src="~/media/@mediaItem.StringId" controls="controls"></audio></td>
            </tr>
        }

    }
    @if (Model.MediaItems.Where(m => m.ContentType.Contains("video/")).Count() > 0)
    {

        foreach (var mediaItem in Model.MediaItems.Where(m => m.ContentType.Contains("video/")))
        {
            <tr>
                <th>@mediaItem.Caption</th>
                <td><video src="~/media/@mediaItem.StringId" controls="controls"></video></td>
            </tr>
        }

    }
    @if (Model.MediaItems.Where(m => m.ContentType.Contains("application/")).Count() > 0)
    {

        foreach (var mediaItem in Model.MediaItems.Where(m => m.ContentType.Contains("application/")))
        {
            <tr>
                <th>@mediaItem.Caption</th>
                <td><a href="~/media/@mediaItem.StringId">@mediaItem.Caption</a></td>
            </tr>
        }

    }
</table>

<p>
    @if (userAccount.HasRoleClaim("Coordinator"))
    {
        @Html.ActionLink("Add a new Album", "AddAlbum", "Artists", new { id = Model.Id }, new { @class = "btn btn-secondary btn-sm" });
    }
    @if (userAccount.HasRoleClaim("Executive"))
    {
        @Html.ActionLink("Add media for this Artist", "AddMedia", "Artists", new { id = Model.Id }, new { @class = "btn btn-secondary btn-sm" });
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Artists/Index.cshtml
@model IEnumerable<Assignment5.ViewModels.ArtistBaseViewModel>

@{
    ViewBag.Title = "Artists";
    var userAccount = new Assignment5.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
}

<h2 style="text-align: center">@ViewBag.Title</h2>

@if (userAccount.HasRoleClaim("Executive"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table table-borderless table-striped" style="table-layout: fixed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BirthName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthOrStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Executive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlArtist)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BirthName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthOrStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Executive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="@item.UrlArtist" alt="@item.Name" style="width:100%; max-width:150px" />
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Artists", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
            </td>
        </tr>
    }

</table>